"""inicial

Revision ID: 79fa0d3f6ae0
Revises: 
Create Date: 2026-08-24 13:26:31.347502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79fa0d3f6ae0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuracao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('limiar_bug_mediana', sa.Float(), nullable=False),
    sa.Column('limiar_promo_mediana', sa.Float(), nullable=False),
    sa.Column('limiar_bug_queda', sa.Float(), nullable=False),
    sa.Column('limiar_promo_queda', sa.Float(), nullable=False),
    sa.Column('percentil_curva', sa.Integer(), nullable=False),
    sa.Column('min_lojas_mediana', sa.Integer(), nullable=False),
    sa.Column('silencio_inicio_hora', sa.Integer(), nullable=False),
    sa.Column('silencio_fim_hora', sa.Integer(), nullable=False),
    sa.Column('lojas_desligadas', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ofertas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loja', sa.String(length=32), nullable=False),
    sa.Column('id_na_loja', sa.String(length=64), nullable=False),
    sa.Column('titulo', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('url_imagem', sa.Text(), nullable=True),
    sa.Column('part_number', sa.String(length=64), nullable=True),
    sa.Column('chave_canonica', sa.String(length=128), nullable=True),
    sa.Column('marca', sa.String(length=32), nullable=True),
    sa.Column('linha', sa.String(length=32), nullable=True),
    sa.Column('capacidade_gb', sa.Integer(), nullable=True),
    sa.Column('modulos', sa.Integer(), nullable=True),
    sa.Column('velocidade_mts', sa.Integer(), nullable=True),
    sa.Column('latencia_cl', sa.Integer(), nullable=True),
    sa.Column('formato', sa.String(length=16), nullable=False),
    sa.Column('rgb', sa.Boolean(), nullable=False),
    sa.Column('condicao', sa.String(length=16), nullable=False),
    sa.Column('vendedor', sa.String(length=128), nullable=True),
    sa.Column('reputacao_vendedor', sa.Float(), nullable=True),
    sa.Column('primeira_vez_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ultima_vez_em', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('loja', 'id_na_loja', name='uq_oferta_loja_id')
    )
    op.create_index('ix_oferta_chave', 'ofertas', ['chave_canonica'], unique=False)
    op.create_index('ix_oferta_part_number', 'ofertas', ['part_number'], unique=False)
    op.create_table('rodadas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('iniciada_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('terminada_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ofertas_vistas', sa.Integer(), nullable=False),
    sa.Column('precos_gravados', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alertas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('oferta_id', sa.Integer(), nullable=False),
    sa.Column('selo', sa.String(length=8), nullable=False),
    sa.Column('sinal', sa.String(length=24), nullable=False),
    sa.Column('preco_centavos', sa.Integer(), nullable=False),
    sa.Column('referencia_centavos', sa.Integer(), nullable=True),
    sa.Column('desvio_percentual', sa.Float(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notificado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dispensado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['oferta_id'], ['ofertas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('precos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('oferta_id', sa.Integer(), nullable=False),
    sa.Column('rodada_id', sa.Integer(), nullable=False),
    sa.Column('preco_centavos', sa.Integer(), nullable=False),
    sa.Column('preco_original_centavos', sa.Integer(), nullable=True),
    sa.Column('em_estoque', sa.Boolean(), nullable=False),
    sa.Column('centavos_por_gb', sa.Integer(), nullable=True),
    sa.Column('observado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['oferta_id'], ['ofertas.id'], ),
    sa.ForeignKeyConstraint(['rodada_id'], ['rodadas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_preco_oferta_data', 'precos', ['oferta_id', 'observado_em'], unique=False)
    op.create_table('saude_adaptadores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rodada_id', sa.Integer(), nullable=False),
    sa.Column('loja', sa.String(length=32), nullable=False),
    sa.Column('sucesso', sa.Boolean(), nullable=False),
    sa.Column('qtd_ofertas', sa.Integer(), nullable=False),
    sa.Column('erro', sa.Text(), nullable=True),
    sa.Column('duracao_ms', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rodada_id'], ['rodadas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('saude_adaptadores')
    op.drop_index('ix_preco_oferta_data', table_name='precos')
    op.drop_table('precos')
    op.drop_table('alertas')
    op.drop_table('rodadas')
    op.drop_index('ix_oferta_part_number', table_name='ofertas')
    op.drop_index('ix_oferta_chave', table_name='ofertas')
    op.drop_table('ofertas')
    op.drop_table('configuracao')
    # ### end Alembic commands ###
